#!/usr/bin/env ansible-playbook -i inventory
#
- name: Provision the instances
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:

     - include: tasks/vpc.yaml
     #- include: tasks/keypair.yaml name="priv_key"
     #- include: tasks/securitygroup.yaml
     #- include: tasks/instance.yaml keypair="priv_key"
     #- include: tasks/rds.yaml name="RDS"
