- name: make sure local keys directory exists
  file:
    state: directory
    path: "{{ playbook_dir }}/keys"

- name: remove existing keypair when force_keypair=True
  ec2_key:
    name: "{{ name|default('default') }}"
    region: "{{ region|default('us-east-1') }}"
    state: absent
  when: force_keypair|default(False)

- name: make a keypair with the specified name
  ec2_key:
    name: "{{ name|default('default') }}"
    region: "{{ region|default('us-east-1') }}"
    wait: yes
  register: key_data

- name: save the key file to local host
  copy:
    content: "{{ key_data.key.private_key }}"
    dest: "keys/{{ name|default('default') }}"
    mode: 0600
  when: key_data.key.private_key|default(0)

- name: debug keypair
  debug: msg="{{ key_data }}"
