- include: install_repo.yaml

- name: install packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-agent
    - zabbix-sender

- name: configure zabbix_agent.conf
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  sudo: yes
  notify: restart zabbix-agent

- name: ensure zabbix-agent service
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  sudo: yes
