- include: install_repo.yaml

- name: install packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-server
    - zabbix-server-pgsql
    - zabbix-get
    - zabbix-web-pgsql

- name: configure zabbix-server.conf
  sudo: yes
  template:
    dest: /etc/zabbix/zabbix_server.conf
    src: zabbix_server.conf.j2
    owner: root
    group: zabbix
    mode: 0640
  notify: restart zabbix-server

- name: Configure zabbix-site
  sudo: yes
  template:
    dest: /etc/httpd/conf.d/zabbix.conf
    src: zabbix-site.conf.j2
    owner: apache
    group: apache
    mode: 0640
  notify: restart httpd

- name: configure zabbix.conf.php
  sudo: yes
  template:
    dest: /etc/zabbix/web/zabbix.conf.php
    src: zabbix.conf.php.j2
    owner: apache
    group: apache
    mode: 0644
  notify: restart zabbix-server

- name: ensure started zabbix-server
  sudo: yes
  service:
    name: zabbix-server
    state: started
    enabled: yes

- name: check installed zabbix-server-pgsql version
  shell: zabbix_server_pgsql --version | awk '/Zabbix/{ sub(/v/, "", $3); print $3 }'
  register: installed_version

- name: Make sure the zabbix_html_path directory exists
  file:
    path: "{{ zabbix_html_path }}"
    owner: apache
    group: apache
    mode: 0755
    recurse: yes
    state: directory


- name: Copy zabbix gui files to zabbix_html_path
  sudo: yes
  copy:
    src: /usr/share/zabbix/
    dest: "{{ zabbix_html_path }}"
    directory_mode: yes
    owner: apache
    group: apache
    mode: 0755
    directory_mode: 0755
  notify: restart httpd

- name: migration zabbix database
  command: >
    psql --host={{ zabbix_server_DBHost }}
         --user={{ zabbix_server_DBUser }}
         --dbname={{ zabbix_server_DBName}}
         --file {{ item }}
  with_items:
    - /usr/share/doc/zabbix-server-pgsql-{{ installed_version.stdout }}/create/schema.sql
    - /usr/share/doc/zabbix-server-pgsql-{{ installed_version.stdout }}/create/images.sql
    - /usr/share/doc/zabbix-server-pgsql-{{ installed_version.stdout }}/create/data.sql
  notify: restart zabbix-server
