---
# handlers file for PostgreSQL

- name: restart postgresql
  service: name=postgresql93 state=restarted
  sudo: yes

- name: start postgresql
  service: name=postgresql93 state=started
  sudo: yes

- name: reload postgresql
  service: name=postgresql93 state=reloaded
  sudo: yes
